initial 1.89.0 ver
AnacondaRecipes/ansicon-feedstock pull request #1
Opened 2023-12-04 12:49 UTC by M-Waszkiewicz-Anaconda

ansicon 1.89.0 - ANSI console for windows,  dependency for jinxed -> blessed
- [upstream] (https://github.com/Rockhopper-Technologies/ansicon/tree/1.89.0)
- [requirements] (https://github.com/Rockhopper-Technologies/ansicon/blob/1.89.0/setup.py)
- [CF](https://github.com/conda-forge/ansicon-feedstock)
- update CF recipe to satisfy linter
- removed cross compilation support
- added tests
- have to skip test_unload_fail, because load/unload used the same location always, see

```
    def test_unload_fail(self):
        """
        Raise an Error when operation fails
        """

        # Load and capture handle
        ansicon.load()
        old_dll = ansicon._ANSICON.dll  # pylint: disable=protected-access

        # Unload
        ansicon.unload()

        # Force failure with old handle
        ansicon._ANSICON.dll = old_dll  # pylint: disable=protected-access
        with self.assertRaises(WindowsError):  # pylint: disable=undefined-variable
>           ansicon.unload()
E           AssertionError: OSError not raised

```

2023-12-04 12:50 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
Traceback (most recent call last):
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/_renderer.py", line 235, in render
    return ruamel.load(yaml_text.replace("\t", " ").replace("%", " "))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 216, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/parser.py", line 146, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/parser.py", line 612, in parse_block_mapping_key
    raise ParserError(
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 28, column 2:
     source_files:
     ^ (line: 28)
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 30, column 3:
      imports:
      ^ (line: 30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/lint/__init__.py", line 734, in lint_file
    recipe = _recipe.Recipe.from_file(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/recipe.py", line 244, in from_file
    raise exc
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/recipe.py", line 235, in from_file
    recipe._load_from_string(text.read())
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/recipe.py", line 167, in _load_from_string
    self.render()
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/recipe.py", line 284, in render
    self.meta = renderer.render(self.recipe_dir, self.dump(), self.selector_dict, self.renderer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/_renderer.py", line 262, in render
    raise YAMLRenderFailure(recipe_dir, line=exc.problem_mark.line)
percy.render.exceptions.YAMLRenderFailure: /tmp/abs_9fwz0sdwae/clone/recipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/linter/bin/conda-lint", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/run.py", line 126, in main
    result = linter.lint(recipes, subdir, args.variant_config_files, args.exclusive_config_files, args.fix)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/lint/__init__.py", line 634, in lint
    msgs = self.lint_file(
           ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/lint/__init__.py", line 751, in lint_file
    recipe = _recipe.Recipe(recipe_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/percy/render/recipe.py", line 106, in __init__
    self.recipe_dir = recipe_file.parent
                      ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'parent'

ERROR conda.cli.main_run:execute(49): `conda run conda-lint /tmp/abs_9fwz0sdwae/clone` failed. (See above for error)
</details>

2023-12-04 19:26 UTC, cbouss approved these changes
LGTM

2023-12-04 20:56 UTC, JeanChristopheMorinPerso commented
This package includes pre-compiled binaries: https://inspector.pypi.io/project/ansicon/1.89.0/packages/75/f9/f1c10e223c7b56a38109a3f2eb4e7fe9a757ea3ed3a166754fb30f65e466/ansicon-1.89.0-py2.py3-none-any.whl/

Based on https://github.com/Rockhopper-Technologies/ansicon, the binaries seem to be coming from https://github.com/adoxa/ansicon.

Should we look at compiling the binaries?

2023-12-04 21:38 UTC, M-Waszkiewicz-Anaconda commented
> This package includes pre-compiled binaries: https://inspector.pypi.io/project/ansicon/1.89.0/packages/75/f9/f1c10e223c7b56a38109a3f2eb4e7fe9a757ea3ed3a166754fb30f65e466/ansicon-1.89.0-py2.py3-none-any.whl/
> 
> Based on https://github.com/Rockhopper-Technologies/ansicon, the binaries seem to be coming from https://github.com/adoxa/ansicon.
> 
> Should we look at compiling the binaries?

Yes, I was aware about it, IMO if the tests are passing so good enough for me, but maybe it is not acceptable ?

2023-12-04 21:40 UTC, JeanChristopheMorinPerso commented
@M-Waszkiewicz-Anaconda The main issue with redistributing already compiled binaries is that we don't know whey they come from, we don't know how they were compiled and we don't know if they are safe to use. In other words, the main concern has to do with supply chain security.

2023-12-04 21:43 UTC, ryanskeith approved these changes
The recipe looks good. JC raises some valid concerns.

2023-12-04 21:45 UTC, M-Waszkiewicz-Anaconda commented
> @M-Waszkiewicz-Anaconda The main issue with redistributing already compiled binaries is that we don't know whey they come from, we don't know how they were compiled and we don't know if they are safe to use. In other words, the main concern has to do with supply chain security.

I will do the rebuild then

2023-12-06 14:31 UTC, skupr-anaconda approved these changes
LGTM

2023-12-06 15:02 UTC, JeanChristopheMorinPerso requested changes

2023-12-06 15:02 UTC, JeanChristopheMorinPerso commented on recipe/bld.bat
> +del /F %SRC_DIR%\ansicon\ANSI64.dll
This is not necessary.

2023-12-06 15:02 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +
```suggestion
```

2023-12-06 15:02 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - pytest -v tests -k "not test_unload_fail"
You should document the test failure in the recipe, not the PR description.

2023-12-06 15:02 UTC, JeanChristopheMorinPerso commented on recipe/0001-load-ansicon-library-from-conda-default-location.patch
> ++            self.dll = ctypes.WinDLL("ANSI64.dll", use_last_error=True)
This is technically slightly unsafe since there seems to be no guarantee that our `ANSI64.dll` will be loaded.

From https://docs.python.org/3/library/ctypes.html
>Passing the full path to the DLL is the safest way to ensure the correct library and dependencies are loaded.

We could amybe do something like `os.path.join(os.environ['CONDA_PREFIX'], 'Library', 'bin', 'ANSI64.dll')`

2023-12-06 15:57 UTC, JeanChristopheMorinPerso approved these changes

2023-12-06 17:30 UTC, merged